# Generated by Django 5.0.2 on 2024-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_manager', '0001_initial'),
        ('users', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='trainers',
            field=models.ManyToManyField(through='gym_manager.ClientSchedule', to='users.trainer'),
        ),
        migrations.AddField(
            model_name='client',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='gyms',
            field=models.ManyToManyField(through='gym_manager.TrainerSchedule', to='gym_manager.gym'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='price_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialization',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('М', 'Мужчина'), ('Ж', 'Женщина'), ('Д', 'Другое')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
