version: "3.9"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - fitness_api
    env_file:
      - .env
    environment:
      - NGINX_PROXY=http://fitness_api:${APP_PORT}
  fitness_api:
    depends_on:
      - db
    build: .
    image: fitness_api
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - ENV=PROD
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
